version: "3.7"
services:
    # imagem micro email
    micro_email:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_email
            - queue_micro_email
        networks:
            - microservices
        links:
            - db_micro_email

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8002:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    # mysql micro email
    db_micro_email:
        container_name: db_micro_tera
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3308:3306
        command: mysqld --character-set-server=utf8mb4
                --collation-server=utf8mb4_unicode_ci
                --default-authentication-plugin=mysql_native_password --sql-mode=""
        networks:
            - microservices

    # queue micro email
    queue_micro_email:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_email
        networks:
            - microservices

    #redis
    redis_micro_email:
        image: redis:latest
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
